### ISSUE TITLE
Delete method and group previuly created

### ISSUE THREAD

**Issue by israelpelayo** [ecampbell/moodle-local_uploadenrolmentmethods#10]
Hello, thank you very much for this excellent plugin, it has helped me a lot.
I would like this function to be implemented. When I choose the delete operation, it does delete the enrollment method. However, if I had done the enrollment and creation of the group through this plugin previously, and if I want to perform the delete operation, it only removes the method, but not the group that was created. Is it possible that the group is also deleted?

I really appreciate your work.

**Comment by ecampbell** [comment]
This is a nice idea, but I think it belongs in a different plugin, perhaps one that can manually un-enrol participants, groups and groupings from a course.
