### ISSUE TITLE
Missing strings cause warnings

### ISSUE THREAD

**Issue by annouarf** [ecampbell/moodle-local_uploadenrolmentmethods#11]
Hi Eoin,

While doing QA processes around the define roles functionality, the below warning came out :

**Invalid get_string() identifier: 'uploadenrolmentmethods:add' or component 'tool_uploadenrolmentmethods'. Perhaps you are missing $string['uploadenrolmentmethods:add'] = ''; in C:\wamp64\www\moodle/admin/tool/uploadenrolmentmethods/lang/en/tool_uploadenrolmentmethods.php?
line 353 of \lib\classes\string_manager_standard.php: call to debugging()
line 7284 of \lib\moodlelib.php: call to core_string_manager_standard->get_string()
line 2589 of \lib\accesslib.php: call to get_string()
line 2434 of \lib\accesslib.php: call to get_capability_string()
line 118 of \admin\roles\classes\capability_table_base.php: call to get_capability_docs_link()
line 135 of \admin\roles\classes\capability_table_with_risks.php: call to core_role_capability_table_base->display()
line 708 of \admin\roles\classes\define_role_table_advanced.php: call to core_role_capability_table_with_risks->display()
line 257 of \admin\roles\define.php: call to core_role_define_role_table_advanced->display()**

By adding the two below strings to the tool_uploadenrolmentmethods.php the problem is solved :
**$string['uploadenrolmentmethods:add'] = 'Add/Upload enrolment methods';
$string['uploadenrolmentmethods:delete'] = 'Delete enrolment methods';**

**Comment by levemar** [comment]
I just created a pull request for this : https://github.com/ecampbell/moodle-tool_uploadenrolmentmethods/pull/12

**Comment by ecampbell** [comment]
Fixed in version 1.4
