### ISSUE TITLE
Allow separators different than ","

### ISSUE THREAD

**Issue by ya-d** [ecampbell/moodle-local_uploadenrolmentmethods#2]
Depending on region its a real pain to set the csv delimiter to "," in Excel. It’s unbelievable that you cannot alter the separator in a "professional" spreadsheet and of course not the fault of this plugin.

Still, it’d be awesome to be able to chose the csv delimiter for this plugin. As it is possible for default uploads of courses and users in Moodle. Thanks for considering.

**Comment by ecampbell** [comment]
I have released a new version, 1.3, which fixes this issue.

**Comment by ya-d** [comment]
Thank you so much for taking care of my issues. Great work and highly appreciated!
