### ISSUE TITLE
Cohort not found

### ISSUE THREAD

**Issue by davidpesce** [ecampbell/moodle-local_uploadenrolmentmethods#4]
I've tried quite a few different ways to get this to upload and it always errors with "Cohort not found". I've tried using the database ID, URL id, the ID that I set via Moodle UI. Nothing seems to catch. I'm guessing it's something stupid (on my part). Any idea what I'm doing wrong?

Moodle 3.9.3+ (latest)
Plugin version 1.3.1

**Comment by ecampbell** [comment]
You must use the "Cohort ID" field (not the "Name" field) to identify the cohort. This field is optional when creating a new cohort, but you must fill it in if you want to use this method.

**Comment by davidpesce** [comment]
Here are the headings that I'm using: 

operation | method | shortname | idnumber | disabled | group | role

I think that's my issue...

**Comment by ecampbell** [comment]
You must use commas, not vertical bars, to separate columns

**Comment by davidpesce** [comment]
Yeah, I swapped it from commas to bars to make it easier to read. It's a CSV and has commas.

Here's the CSV:
add,cohort,SN - Homework 1:1,dsdinternal,0,,manager
add,cohort,SN - Homework 1:2,dsdinternal,0,,manager

**Comment by ecampbell** [comment]
Apologies, I've misled you. The plugin now requires column headings. I forgot I added this feature.

**Comment by davidpesce** [comment]
Not to worry. Adding the headings back in gets me back to the cohort not found error.

**Comment by davidpesce** [comment]
I really think it's an issue with my heading names. Can you confirm that my heading names are correct for adding the cohort sync method into an existing course?

operation,method,shortname,idnumber,disabled,group,role

**Comment by davidpesce** [comment]
I'm stumped. Nothing seems to be working.

**Comment by ecampbell** [comment]
Use     operation,method,shortname,metacohort,disabled,group,role

**Comment by davidpesce** [comment]
Bingo! That did it. Thank you!!
