### ISSUE TITLE
v1.3.1 fails to install because of incompatible moodle version number

### ISSUE THREAD

**Issue by davidpesce** [ecampbell/moodle-local_uploadenrolmentmethods#7]
Getting the following error when installing on 3.9.3+:
![image](https://user-images.githubusercontent.com/3988068/101395822-7855b780-3898-11eb-9465-dc0d8b36ff2c.png)

**Comment by davidpesce** [comment]
Fixed via PR #6

**Comment by ecampbell** [comment]
Fixed in version 1.3.2
