### ISSUE TITLE
Add ability to enrol multiple roles as a cohort sync enrolment

### ISSUE THREAD

**Issue by dhandby** [ecampbell/moodle-local_uploadenrolmentmethods#9]
Add ability to enrol multiple roles as a cohort sync enrolment

Example 1 which works.
Operation,method,shortname,metacohort,disabled,role
add,cohort,Test1,Student-cohort,0,rs
add,cohort,Test2,Student-cohort,0,rs

Example 2 which fails
Operation,method,shortname,metacohort,disabled,role
add,cohort,Test1,Student-cohort,0,rs (Have also tried combinations of rs,ri in this line) nothing seems to work.
add,cohort,Test1,Student-cohort,0,ri

**Comment by ecampbell** [comment]
Try duplicating the cohort so that it has a different name but contains the same members.

**Comment by dhandby** [comment]
Hi,

Thanks for the update. Your comment does indeed work, however we need the 1 cohort sync added via 2 seperate roles which sometimes we have 1000 students for RS and a functionality exists in RI for invigilation.

We can't duplicate the cohorts with a different name I'm afraid. Do you know how much work would be involved in developing the code to allow for the case above?

Thanks,
Dean

**Comment by ecampbell** [comment]
How about creating an intermediate meta course that enrols the students from the cohort as a standard role. Then use the add meta enrolment method to enrol those students in your target course with the role you want (RS). So the students in a single cohort are enrolled twice, once via cohort enrolment, and a second time via meta-course enrolment. This should prevent the tool from complaining.

**Comment by dhandby** [comment]
We have 500 course shells and 120,000 students this would not be a viable option. Thanks anyway

**Comment by ecampbell** [comment]
Hi Dean, This turned out to be very easy to do, so I created a new version v1.3.3 that you can download from https://github.com/ecampbell/moodle-tool_uploadenrolmentmethods/archive/refs/tags/v1.3.3.zip
Can you take a look and let me know if it works, and I'll release it to the Moodle plugins database

**Comment by dhandby** [comment]
Thankyou so much! This will save us sooo much time/effort in enabling this. Yes it works as intended now with no issues.

2 | Add | Cohort sync | TEST-QUIZ | 2 | student-cohort |   | rs | Enabled | Enrolment instance created
  | 3 | Add | Cohort sync | TEST-QUIZ | 2 | student-cohort |   | remoteinvigilated | Enabled | Enrolment instance created

**Comment by dhandby** [comment]
Looking forward for it to be released as an official update.
